name: Scala build and test
on: [push, pull_request]

jobs:
  # Label of the container job
  mvn-build-test:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: maven:3.8-openjdk-11

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Cache mvn cache
        id: mvn-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}--${{ hashFiles('pom.xml') }}

      - name: Verify
        run: mvn verify

      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: rpki-irr-bgp-stats-dist
          path: target/rpki-irr-bgp-stats-dist.tar.gz

      - name: Upload reports
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: |
            target/surefire-reports/**/*

  docker:
    runs-on: ubuntu-latest
    needs: mvn-build-test
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: checkout sources
        uses: actions/checkout@v2

      - name: Fetch dist
        uses: actions/download-artifact@v2
        with:
          name: rpki-irr-bgp-stats-dist

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build_rpki_irr_bgp_stats
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ripencc/rpki-irr-bgp-stats:latest
          labels: "org.label-schema.vcs-ref=${{ github.sha }}"
          build-args: |
            RPKI_IRR_BGP_STATS_DIST=./rpki-irr-bgp-stats-dist.tar.gz

      - name: Image digest
        run: echo ${{ steps.docker_build_rpki_irr_bgp_stats.outputs.digest }}
